language: c

# Default windows jobs
os: windows

script:
  # https://travis-ci.community/t/using-cl-exe-for-32-and-64-bits/1905/2
  - cl.exe /LD ./c/qrcodegen.c

# don't notify me when things fail
notifications:
  email: false
