language: c

# Default windows jobs
os: windows
  
script:
  # https://travis-ci.community/t/using-cl-exe-for-32-and-64-bits/1905/2
  - mingw32-make.exe ./c/Makefile all
  

# don't notify me when things fail
notifications:
  email: false
