language: c

# Default linux jobs
os: windows

script:
  - cl.exe /D_USRDLL /D_WINDLL qrcodegen.h qrcodegen.c qrcodegen-worker.c qrcodegen-test.c qrcodegen-demo.c /link /DLL /OUT:<qrcodegen.dll

# don't notify me when things fail
notifications:
  email: false
